version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["component/dependencies"]

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["component/dependencies"]

  # Maintain dependencies for Golang
  - package-ecosystem: "gomod"
    directory: "/src/go/nerdctl-stub"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["component/dependencies"]

  - package-ecosystem: "gomod"
    directory: "/src/go/wsl-helper"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels: ["component/dependencies"]
