task:
  trigger_type: manual
  matrix:
    - name: Linux - RD E2E/Integration Tests
      timeout_in: 60
      container:
        image: ubuntu:20.04
        kvm: true
        cpu: 4
        memory: 8G
      env:
        DEBIAN_FRONTEND: noninteractive
        CI: 1
      install_deps_script: |
        apt-get update
        apt-get install -y --no-install-recommends apt-transport-https ca-certificates gcc g++ curl git golang openssh-client make netcat sudo qemu-system-x86 qemu-utils vim
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && apt-get install -y nodejs && node --version && npm -v
        apt-get install -y xvfb gconf-service libasound2 libatk1.0-0 libc6 libcairo2 libcups2 \
        libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 \
        libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 \
        libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 \
        libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
# apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
  

  prepate_user_script: |
    groupadd -g $(stat -c '%g' /dev/kvm) kvm
    useradd -m -G kvm rancheruser
    cp -rf . /home/rancheruser

  build_script: |
    chown -R rancheruser:rancheruser /home/rancheruser
    chown -R rancheruser:rancheruser /dev/kvm
    sudo -iu rancheruser npm install

  test_script: |
    export KUBECONFIG=/home/rancheruser/.kube/config
    export NODE_ENV=test
    sudo -iu rancheruser npm run test:e2e:first:ci && npm run test:e2e:ci:linux

  on_failure:
    logs_artifacts:
      path: | 
        ./home/rancheruser/*.png
        ./home/rancheruser/chromedriver.log
        ./home/rancheruser/wdio.log