# task:
#   name: RD E2E/Integration tests
#   timeout_in: 30
#   container:
#     image: ubuntu:20.04
#     kvm: 'true'
#     cpu: 4
#     memory: 8G
#   env:
#     DEBIAN_FRONTEND: noninteractive

#   install_deps_script: |
#     apt-get update
#     apt-get install -y --no-install-recommends ca-certificates gcc g++ curl git golang openssh-client make netcat sudo
#     curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && apt-get install -y nodejs && node --version && npm -v
#     apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

#   node_modules_cache:
#     folder: node_modules
#     fingerprint_script: cat package-lock.json
#     populate_script: npm ci
#   test_script: |
#     chmod +x ./node_modules
#     npm run test:e2e:ci

task:
  matrix:
    - name: Linux - RD E2E/Integration Tests
      timeout_in: 30
      container:
        image: ubuntu:20.04
        kvm: 'true'
        cpu: 4
        memory: 8G
      env:
        DEBIAN_FRONTEND: noninteractive 

      install_deps_script: |
        apt-get update
        apt-get install -y --no-install-recommends ca-certificates gcc g++ curl git golang openssh-client make netcat sudo
        curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash - && apt-get install -y nodejs && node --version && npm -v
        apt-get install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb

    - name: macOS - RD E2E/Integration Tests
      timeout_in: 30
      osx_instance:
        image: big-sur-base
        kvm: 'true'
        cpu: 4
        memory: 8G
      env:
        DEBIAN_FRONTEND: noninteractive 

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci
  test_script: |
    chmod +x ./node_modules
    npm run test:e2e:ci