name: Feature Request
description: Suggest a feature or idea to Rancher Desktop
labels: ["enhancement"]
body:
- type: checkboxes
  attributes:
    label: Preflight Checklist
    description: Please ensure you've completed the following.
    options:
      - label: I have searched the [issue tracker](https://github.com/rancher-sandbox/rancher-desktop/issues) for a feature request that matches the one I want to file, without success.
        required: true
- type: textarea
  attributes:
    label: Problem Description
    description: A clear and concise description of what enhancement you'd like.
  validations:
    required: true
- type: textarea
  attributes:
    label: Proposed Solution
    description: Describe the solution you'd like in a clear and concise manner.
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional Information
    description: Add any other context/information about the problem here.
  validations:
    required: false