# Default Lima configuration; parts will be overridden in code.

ssh:
  loadDotSSHPubKeys: false
firmware:
  legacyBIOS: true
containerd:
  system: false
  user: false
# Provisioning scripts run on every boot, not just initial VM provisioning.
provision:
- # When the ISO image is updated, only preserve selected data from /etc but otherwise use the new files.
  # Update files in /usr/local on the data volume from the new versions on the ISO.
  mode: system
  script: |
    #!/bin/sh
    set -o errexit -o nounset -o xtrace
    mkdir -p /bootfs
    mount --bind / /bootfs
    # /bootfs/etc is empty on first boot because it has been moved to /mnt/data/etc by lima
    if [ -f /bootfs/etc/os-release ] && ! diff -q /etc/os-release /bootfs/etc/os-release; then
      cp /etc/machine-id /bootfs/etc
      cp /etc/ssh/ssh_host* /bootfs/etc/ssh/
      mkdir -p /etc/docker /etc/rancher
      cp -pr /etc/docker /bootfs/etc
      cp -pr /etc/rancher /bootfs/etc

      rm -rf /mnt/data/etc.prev
      mkdir /mnt/data/etc.prev
      mv /etc/* /mnt/data/etc.prev
      mv /bootfs/etc/* /etc

      # install updated files from /usr/local, e.g. nerdctl, buildkit, cni plugins
      cp -pr /bootfs/usr/local /usr

      # lima has applied changes while the "old" /etc was in place; restart to apply them to the updated one.
      reboot
    fi
    umount /bootfs
    rmdir /bootfs
- # Make sure hostname doesn't change during upgrade from earlier versions
  mode: system
  script: |
    #!/bin/sh
    hostname lima-rancher-desktop
- # Create host.rancher-desktop.internal, lima-rancher-desktop, and host.docker.internal aliases for host.lima.internal
  mode: system
  script: |
    #!/bin/sh
    sed -i 's/host.lima.internal.*/host.lima.internal lima-rancher-desktop host.rancher-desktop.internal host.docker.internal/' /etc/hosts
- # Clean up filesystems
  mode: system
  script: |
    #!/bin/sh
    set -o errexit -o nounset -o xtrace
    # During boot is the only safe time to delete old k3s versions.
    rm -rf /var/lib/rancher/k3s/data
    # Delete all tmp files older than 3 days.
    find /tmp -depth -mtime +3 -delete
- # Make mount-points shared.
  mode: system
  script: |
    #!/bin/sh
    set -o errexit -o nounset -o xtrace
    for dir in / /etc /tmp /var/lib; do
      mount --make-shared "${dir}"
    done
- # This sets up cron (used for logrotate)
  mode: system
  script: |
    #!/bin/sh
    # Move logrotate to hourly, because busybox crond only handles time jumps up
    # to one hour; this ensures that if the machine is suspended over long
    # periods, things will still happen often enough.  This is idempotent.
    mv -n /etc/periodic/daily/logrotate /etc/periodic/hourly/
    rc-update add crond default
    rc-service crond start
- # Ensure the user is in the docker group to access the docker socket
  mode: system
  script: |
    set -o errexit -o nounset
    . /mnt/lima-cidata/lima.env
    set -o xtrace
    usermod --append --groups docker "${LIMA_CIDATA_USER}"
portForwards:
- guestPortRange: [1, 65535]
  hostIP: "0.0.0.0"
