name: E2E Test

on:
  workflow_dispatch: {}
  schedule:
    - cron: '0 7 * * 1,3,5'
env:
  # Force terminal colors. @see https://www.npmjs.com/package/colors
  FORCE_COLOR: 1
jobs:
  e2e-test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-10.15, windows-2019, ubuntu-20.04]

    name: RD E2E Test - ${{ matrix.os}}
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.16'

      - name: Build CI
        run: npm ci
        env:
          DEBUG: pw:install
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

      - name: Install Playwrigth dependencies
        run: npx playwright install-deps

      - name: Run Linter check
        run: npm run lint:nofix

      - name: Run E2E Tests - ${{ matrix.os }}
        if: ${{ matrix.os != 'ubuntu-20.04' }}
        run: npm run test:e2e

      - name: Install required packages for Linux
        if: ${{ matrix.os == 'ubuntu-20.04'}}
        run: |
          sudo apt-get update
          sudo apt-get install -y libwoff1 libopus0 libwebp6 libwebpdemux2 libenchant1c2a libgudev-1.0-0 libsecret-1-0 \
                             libhyphen0 libgdk-pixbuf2.0-0 libegl1 libgles2 libnotify4 libxslt1.1 \
                             gstreamer1.0-gl gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad \
                             libgbm1 xvfb
          sudo sysctl kernel.unprivileged_userns_clone=1

      - name: Run E2E Tests - Linux with xvfb
        if: ${{ matrix.os == 'ubuntu-20.04'}}
        run: npm run test:e2e:ci:linux
        env:
          DEBUG: pw:browser*

      - name: Getting logs - Linux
        if: ${{ failure() && matrix.os == 'ubuntu-20.04'}}
        run: |
          zip -r linux-Runner-Logs.zip /home/runner/.local/share/rancher-desktop/logs/*

      - uses: actions/upload-artifact@v2
        if: failure() # upload when previous step has failed
        with:
          name: PW-E2E-Logs-${{ matrix.os }}
          path: |
            ./linux-Runner-Logs.zip
            ./wdio.log
            ./*.jpeg
            ./pw-trace.zip
